__default__:
  # exchange <staff> with your SLURM account id below
  account: snic2021-22-184

  # directories for slurm logs (no need to change these)
  output: "slurm/logs/{rule}.{wildcards}.out"
  error: "slurm/err/{rule}.{wildcards}.err"

megahit:
  time: 14400
  constraint: "mem1TB"
kraken_pe:
  time: 14400
contigtax_search:
  time: 14400
pfam_scan:
  time: 14400
metaspades:
  time: 14400
  constraint: "mem256GB"
